### ISSUE TITLE
KS240 Support - Fan Speed Control and Dimmer 

### ISSUE THREAD

**Issue by MichaelCWarren** [ZeliardM/homebridge-kasa-python#24]
It looks like the python-kasa supports this module, but it doesn't show up in home bridge.  I'm guessing this is because it shows up as a Fan type which is in the unsupported list.  

If you want I can give it a go and try adding it, but I'm guessing you'd be able to do it much faster, and in your preferred way. 

Let me know if you need anything from me.

Thanks!

**Comment by ZeliardM** [comment]
@MichaelCWarren I thought the KS240 had native HomeKit and Matter support. Does it not?

**Comment by ZeliardM** [comment]
@MichaelCWarren If you could grab full logs from the latest beta plug-in with the device. I'd like to have the advanced python logging and debug mode in Homebridge turned on. Thanks!

**Comment by MichaelCWarren** [comment]
It does.  However it would be nice to manage all my Kasa devices in one place.  With one connection type.


On Jan 3, 2025, at 9:34 PM, ZeliardM ***@***.***> wrote:

﻿

@MichaelCWarren<https://github.com/MichaelCWarren> I thought the KS240 had native HomeKit and Matter support. Does it not?

**Comment by MichaelCWarren** [comment]
[homebridge.log-14.txt](https://github.com/user-attachments/files/18305514/homebridge.log-14.txt)

Here are the logs.

I tried to add the device as a manual device, but I don't think it matters.  I don't see the device IP referenced anywhere and the only think I _think_ is relevant is the "Skipping device None due to Native HomeKit or Matter support" line.

Here is the discover "info" found using python-kasa...  not sure this will help.

```
== Discovery Result ==
        Device Type:        SMART.KASASWITCH
        Device Model:       KS240(US)
        IP:                 192.168.4.79
        MAC:                F0-09-0D-A9-19-F6
        Device Id (hash):   8db142d8bcf12a3493d18b903969772f
        Owner (hash):       BFBE699976E922C39FFEB5635BBDE955
        Supports IOT Cloud: True
        OBD Src:            BFBE699976E922C39FFEB5635BBDE955
        Encrypt Type:       KLAP
        HTTP Port:          80
        Login version:      2
```

**Comment by ZeliardM** [comment]
@MichaelCWarren Excellent, I will look into adding support for this and maybe another option for filtering devices with native support if desired.

**Comment by MichaelCWarren** [comment]
I think this is going to help you.

```
== None - KS240 ==
Host: 192.168.4.79
Port: 80
Device state: False
Time:         2025-01-08 17:50:07-05:00 (tz: America/Indiana/Indianapolis)
Hardware:     1.0 (US)
Firmware:     1.0.9 Build 241213 Rel.154621
MAC (rssi):   F0:09:0D:A9:19:F6 (-43)

== Primary features ==

== Information ==
Signal Level (signal_level): 3
Cloud connection (cloud_connection): True
Update available (update_available): None
Check latest firmware (check_latest_firmware): <Action>

== Configuration ==
Auto update enabled (auto_update_enabled): True
LED (led): True

== Debug ==
Device ID (device_id): 803B3E8D9C2FFF7B54EF338A07925F102322AEDE
RSSI (rssi): -43 dBm
SSID (ssid): TheWarrwebs
Reboot (reboot): <Action>
Current firmware version (current_firmware_version): 1.0.9 Build 241213 Rel.154621
Available firmware version (available_firmware_version): None
Homekit setup code (homekit_setup_code): 910-46-430
Device time (device_time): 2025-01-08 17:50:07-05:00

== Children ==

	== Fan (None) ==

	== Primary features ==
	State (state): True
	Fan speed level (fan_speed_level): 2 (range: 0-4)

	== Information ==
	Overheated (overheated): False

	== Configuration ==
	Fan sleep mode (fan_sleep_mode): False

	== Debug ==
	Device ID (device_id): 803B3E8D9C2FFF7B54EF338A07925F102322AEDE00
	Reboot (reboot): <Action>

	== Fan Lights (None) ==

	== Primary features ==
	State (state): False
	Brightness (brightness): 10 (range: 0-100)

	== Information ==
	Overheated (overheated): False

	== Configuration ==
	Light preset (light_preset): *Not set* Light preset 1 Light preset 2 Light preset 3 Light preset 4 Light preset 5
	Smooth transition on (smooth_transition_on): 1 (range: 0-60)
	Smooth transition off (smooth_transition_off): 1 (range: 0-60)

	== Debug ==
	Device ID (device_id): 803B3E8D9C2FFF7B54EF338A07925F102322AEDE01
	On since (on_since): None
	Reboot (reboot): <Action>
```

I got far enough into trying to implement this today to understand I'm not sure how to proceed.

1.  It looks like the switch is just a collection of child switches (probably much like the power strip).
2. The IDs don't contain an underscore like you're expecting.  

Let me know if there is something else you need from me.  

Thanks!

**Comment by ZeliardM** [comment]
@MichaelCWarren Could you grab the CLI kasa --username 'username' --password 'password' --host IP_ADDRESS sysinfo

Put in your username and password and the ip of the new switch. I'd like to see what the sysinfo comes out as.

You can scrub personal info if needed.
Thanks!

**Comment by MichaelCWarren** [comment]
```
== System info ==
{'avatar': '',
 'device_id': '803B3E8D9C2FFF7B54EF338A07925F102322AEDE',
 'fw_id': '00000000000000000000000000000000',
 'fw_ver': '1.0.9 Build 241213 Rel.154621',
 'has_set_location_info': True,
 'hw_id': '9BAD152014738F0E3280642ED371F035',
 'hw_ver': '1.0',
 'ip': '192.168.4.79',
 'lang': 'en_US',
 'latitude': '',
 'longitude': '',
 'mac': 'F0-09-0D-A9-19-F6',
 'model': 'KS240',
 'nickname': '',
 'oem_id': '2C46A55D4E2992A744968B8831EC6F99',
 'region': 'America/Indiana/Indianapolis',
 'rssi': -43,
 'signal_level': 3,
 'specs': 'US',
 'ssid': 'VGhlV2FycndlYnM=',
 'time_diff': -300,
 'type': 'SMART.KASASWITCH'}
```

**Comment by rytilahti** [comment]
The KS240 indeed exposes itself using child devices (one for light, one for fan), but there was also something odd in its implementation which forced us to make some hacks inside the library (or in our homeassistant integration, which wants this device to be "one" device only).

https://github.com/python-kasa/python-kasa/blob/master/tests/fixtures/smart/KS240(US)_1.0_1.0.7.json and other KS240 fixtures in our collection might be useful for you, too.

**Comment by ZeliardM** [comment]
@rytilahti Can the child devices be accessed through the CLI?

**Comment by rytilahti** [comment]
@ZeliardM yupp, most commands accept `--child` which takes the child's device id (and perhaps its name? `--help` probably tells if so) as a parameter.

**Comment by ZeliardM** [comment]
@rytilahti Awesome, thanks!

@MichaelCWarren I'm going to think on this one a bit and see if I can figure out a way to either combine these or separate them out into individual devices. I'll let you know when I have something for you to test!

**Comment by ZeliardM** [comment]
@rytilahti Excellent, thanks! As long as I can parse the information about the children from the device the same in the library, I should be good to implement them.

@MichaelCWarren I think I have something close to testing for this, may try and work a little more on it this weekend and have something for you on Monday to try for me.

**Comment by ZeliardM** [comment]
@MichaelCWarren I am close to having something to test, will iron out a few more things this weekend and let you know. Thanks!

**Comment by ZeliardM** [comment]
@MichaelCWarren try beta.26 and let me know what it does. there's a new option to turn off blocking for Native HomeKit devices.

**Comment by MichaelCWarren** [comment]
@ZeliardM So very close!  Looks like it's functioning, except I believe HomeKit treats the fan speed as 0-100 and Kasa uses a 0-4 range. My fan is showing 1/2 speed in Kasa and 2% in HomeKit.

**Comment by ZeliardM** [comment]
@MichaelCWarren Ah, ok, I'll mess with the conversions then a little more. I got them on the way out, but I think I missed them on the way in, lol

**Comment by MichaelCWarren** [comment]
> @ZeliardM So very close!  Looks like it's functioning, except I believe HomeKit treats the fan speed as 0-100 and Kasa uses a 0-4 range. My fan is showing 1/2 speed in Kasa and 2% in HomeKit. 

Scratch that. It looks like it's working okay, but it's not "snapping" to the correct increments. For example, 53% is really 75%, does that make sense?![image](https://github.com/user-attachments/assets/6565aa9b-8add-4c64-863e-13776983957a)

**Comment by ZeliardM** [comment]
@MichaelCWarren Ah, gotcha. Ok, I'll keep poking around.

**Comment by MichaelCWarren** [comment]
> @MichaelCWarren Ah, ok, I'll mess with the conversions then a little more. I got them on the way out, but I think I missed them on the way in, lol

This makes sense, I saw a 2% initially. That would be 50% for Kasa.

**Comment by MichaelCWarren** [comment]
@ZeliardM After a restart I'm now getting this error in the logs and it appears to have created a new device...

```
[20/01/2025, 09:20:42] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Updated sys_info for device: DeviceType.WallSwitch_192.168.75.63
[20/01/2025, 09:20:42] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Service not found for child device: Master Bedroom Fan or previous Kasa device is undefined
```

I'll try to see if I can recreate it

**Comment by MichaelCWarren** [comment]
@ZeliardM Now I can't get it to recognize the device as a Fan at all.  It thinks they are both lights.  I've tried removing the accessory from the cache, but that doesn't seem to work.

**Comment by ZeliardM** [comment]
@MichaelCWarren Can you get me full logs with the advanced python logging and debug so I can see what it's doing?

**Comment by MichaelCWarren** [comment]
[log.txt](https://github.com/user-attachments/files/18479048/log.txt)

The device in question is 192.168.75.63.

Ignore the giant list of manual devices, I'm in the process of moving all of the switches to a separate VLAN.

Also, it looks like we're treating every device as a HomeKit one?

**Comment by ZeliardM** [comment]
I gotcha. Um, yea, the toggle treats all devices as HomeKit devices. I may see if there's a way I can do it if it's a manual device it will add it as HomeKit?

**Comment by MichaelCWarren** [comment]
I don't know if that makes sense.  I only really have the one HomeKit device.  The manual devices are because of device discovery not crossing subnets.  Not that it probably matters from an end user standpoint.

**Comment by ZeliardM** [comment]
Hmm, that may be. Let me look at the logs and I'll go from there. Thanks!

**Comment by ZeliardM** [comment]
@MichaelCWarren Ok, I found the issues I believe, give beta.27 a shot. As for the HomeKit devices, the toggle turns on discovery for every device, even if it has Native HomeKit/Matter support. The only other way to do it, would be to have a flag for manual devices and if it's set to enable that device only, that would require a little more work since it's in the config for each device. I'll have to think on it a bit more. The reason it wasn't finding the fan was because of the service check and the fan_speed_level being 0, so I fixed it to see if the fan_speed_level was there at all and it should make it a Fanv2 service again. I also think I fixed the value snapping and conversions for fan_speed_level as well.

**Comment by MichaelCWarren** [comment]
Looks like the fan is recognized now.  Unfortunately I'm not at home to test the fan and stuff, but we are still getting the same error message.

```
[1/20/2025, 6:15:41 PM] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Service not found for child device: Master Bedroom Fan or previous Kasa device is undefined
```

[homebridge.log-19.txt](https://github.com/user-attachments/files/18481259/homebridge.log-19.txt)

**Comment by MichaelCWarren** [comment]
Setting the Fan from the Wall (or from the HomeKit side), shows appropriately in home bridge, however, there is no change when setting from the homebridge accessory side.  I don't even see any log message for it.

**Comment by ZeliardM** [comment]
That's weird because HomeKit and Homebridge should offer the same calls.

**Comment by MichaelCWarren** [comment]
It's strange for sure.  The light works fine.  I'd say it has something to do with that error.

**Comment by ZeliardM** [comment]
Ok, I'll look at the whole log and let you know.

**Comment by ZeliardM** [comment]
Try deleting the accessory again now that you have beta.27

**Comment by MichaelCWarren** [comment]
I tried that earlier as well.  The error indeed goes away but something causes it to come back.  I think it's when the fan is controlled from the Home app.  I'll confirm when I get home, but I can't due to people sleeping in that room at the moment :-)

**Comment by ZeliardM** [comment]
Hmm, ok. I'll keep looking as well. Thanks!

**Comment by ZeliardM** [comment]
I added another check for the service, can you give beta.28 a shot?

**Comment by MichaelCWarren** [comment]
Looks like it's working so far!  Good work!  I'll let you know if I see anything different.

**Comment by ZeliardM** [comment]
I had another check in there that didn't account for zero amounts on things so it should be good now. I do need to add another to change the active state to inactive if the fan_spee_level is zero or change it to active if it moves from zero. Will let you know.

**Comment by MichaelCWarren** [comment]
@ZeliardM I don't know if the active vs inactive state change is our issue, but something isn't right.  After changing the physical switch or changing the fan speed via the home app, it seems to lose "connection".  I can no longer change the fan at all from the home app, and the state changes don't appear in the logs.  The trigger seems to be when we change the fan via the physical switch.

Unfortunately, I turned off logging last night so I don't have any relevant logs.  Rookie mistake.  I'll turn the logging back on in hopes of catching something.

**Comment by ZeliardM** [comment]
Sounds good, let me know and I'll take a look, thanks!

**Comment by MichaelCWarren** [comment]
I wonder if what I saw wasn't actually the old issue, but a different one.  I just did a quick test and when you change the device from the Kasa/wall side during a discovery, the state never gets updated in HomeKit.  My guess is because we just take the discovery state as the new state and can't check for the change.

**Comment by ZeliardM** [comment]
Yes, the discovery does place a hold on state updates. After the discovery is finished, the state updates should resume 5 seconds later and it should update then at least. Let me follow the logic and see where the breakdown is and I'll let you know.

**Comment by ZeliardM** [comment]
If you can find it in the logs with everything turned on again, that may help as well.

**Comment by MichaelCWarren** [comment]
I was watching the logs as I did it.  As soon as I saw the "Discovering devices..." message.  I turned off the fan, and there was no state change messages (active, fan speed, etc).  I can give you the logs, but there is nothing in them in reference to the change.

[homebridge.log-22.txt](https://github.com/user-attachments/files/18493617/homebridge.log-22.txt)

**Comment by ZeliardM** [comment]
Do you see anything in the logs when you open the Home App about it getting the current characteristic values for the fan and light?

**Comment by MichaelCWarren** [comment]
Here is the stuff that happens when I pull up the Home app.

The device is `DeviceType.WallSwitch_192.168.75.63`

Doesn't say anything about Fan speed there...  and it still isn't updated in the app.

```
[21/01/2025, 12:11:28] [KasaPython] [Kitchen Lights] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Master Bathroom Fan] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Kitchen Island Light] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Basement Closet Light] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Basement Bathroom Light] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Got value for characteristic Brightness: false
[21/01/2025, 12:11:28] [KasaPython] [ Back Porch Light] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Kid’s Bathroom Fan] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Garage Lights] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Main Stairs Light] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Basement Bathroom Fan] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Entryway Lights] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Front Porch Light] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Basement Storage Room] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Kid’s Bathroom Light] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Basement Stairs Light] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Master Bedroom Lights] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Dining Room Lights] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Laundry Room Light] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Living Room Lights] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Office Lights] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Basement Lights] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Main Bathroom Light] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Main Hallway Light] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Master Bedroom Closet Light] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Family Room Front Lights] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Main Bathroom Fan] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Upstairs Hallway Lights] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Utility Room Light] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Master Bathroom Lights] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Family Room Back Lights] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Kitchen Table Lights] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Basement Bathroom Fan Light] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Kitchen Sink Light] Got value for characteristic On: false
[21/01/2025, 12:11:28] [KasaPython] [Master Bedroom Lights] Got value for characteristic Brightness: 34
[21/01/2025, 12:11:28] [KasaPython] [Office Lights] Got value for characteristic Brightness: 34
[21/01/2025, 12:11:28] [KasaPython] [Family Room Back Lights] Got value for characteristic Brightness: 51
[21/01/2025, 12:11:28] [KasaPython] [Dining Room Lights] Got value for characteristic Brightness: 100
[21/01/2025, 12:11:28] [KasaPython] [Living Room Lights] Got value for characteristic Brightness: 51
[21/01/2025, 12:11:28] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Got value for characteristic Brightness: 29
[21/01/2025, 12:11:28] [KasaPython] [Entryway Lights] Got value for characteristic Brightness: 68
[21/01/2025, 12:11:28] [KasaPython] [Family Room Front Lights] Got value for characteristic Brightness: 51
```

**Comment by MichaelCWarren** [comment]
```
  private checkCharacteristics(service: Service, child: ChildDevice) {
    const characteristics = [
      child.fan_speed_level && {
        type: this.platform.Characteristic.RotationSpeed,
        name: this.platform.getCharacteristicName(this.platform.Characteristic.RotationSpeed),
      },
      child.fan_speed_level && {
        type: this.platform.Characteristic.Active,
        name: this.platform.getCharacteristicName(this.platform.Characteristic.Active),
      },
      child.brightness && {
        type: this.platform.Characteristic.On,
        name: this.platform.getCharacteristicName(this.platform.Characteristic.Brightness),
      },
      child.brightness && {
        type: this.platform.Characteristic.Brightness,
        name: this.platform.getCharacteristicName(this.platform.Characteristic.Brightness),
      },
    ].filter(Boolean) as { type: WithUUID<new () => Characteristic>; name: string | undefined }[];

    characteristics.forEach(({ type, name }) => {
      this.getOrAddCharacteristic(service, type, name, child);
    });
  }
```

If fan_speed_level or brightness is 0, that check will fail.  Is it not adding all the characteristics, maybe on a rediscovery?

**Comment by ZeliardM** [comment]
I forgot about those checks, lol, give beta.30 a shot

**Comment by MichaelCWarren** [comment]
I removed the accessory and restarted it, turned it off during a rediscovery, and this is what we got.  

The fan is most definitely off.  

Is it because the fan speed is 50, but the fan is actually off?  

```
[21/01/2025, 12:46:08] [KasaPython] [Kitchen Lights] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Master Bathroom Fan] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Kitchen Island Light] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Basement Closet Light] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Basement Bathroom Light] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [ Back Porch Light] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Kid’s Bathroom Fan] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Garage Lights] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Main Stairs Light] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Basement Bathroom Fan] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Entryway Lights] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Front Porch Light] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Basement Storage Room] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Kid’s Bathroom Light] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Basement Stairs Light] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Master Bedroom Lights] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Dining Room Lights] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Got value for characteristic Brightness: false
[21/01/2025, 12:46:08] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Got value for characteristic Active: 1
[21/01/2025, 12:46:08] [KasaPython] [Living Room Lights] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Office Lights] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Basement Lights] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Main Bathroom Light] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Main Hallway Light] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Laundry Room Light] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Master Bedroom Closet Light] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Family Room Front Lights] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Main Bathroom Fan] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Upstairs Hallway Lights] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Utility Room Light] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Master Bathroom Lights] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Family Room Back Lights] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Kitchen Table Lights] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Basement Bathroom Fan Light] Got value for characteristic On: false
[21/01/2025, 12:46:08] [KasaPython] [Kitchen Sink Light] Got value for characteristic On: false
```

**Comment by ZeliardM** [comment]
Nah, still got a bit to work out on it, will keep trying, give me a bit and I'll push another beta

**Comment by MichaelCWarren** [comment]
Looks like in my previous log I forgot some other messages...

```
[21/01/2025, 12:57:11] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Got value for characteristic Brightness: 29
[21/01/2025, 12:57:11] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Got value for characteristic RotationSpeed: 50
```

So it is pulling the rotation speed.  But it's still the out of date value.

Hope this info helps.

**Comment by ZeliardM** [comment]
It's weird, it took it 3 seconds to get those values in comparison to the others, it should pull it all at once. It should have a Brightness and an On for the dimmer and Active and RotationSpeed for the fan, but brightness is twice and rotationspeed is not lining up. Let me rework a few things on the characteristics.

**Comment by MichaelCWarren** [comment]
I may have pulled the wrong lines.  It didn't take 11 minutes.

```
[21/01/2025, 12:46:08] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Got value for characteristic Brightness: 29
[21/01/2025, 12:46:08] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Got value for characteristic RotationSpeed: 50
```

**Comment by ZeliardM** [comment]
All good, try beta.31 and let me know.

**Comment by MichaelCWarren** [comment]
```
[21/01/2025, 13:48:12] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Got value for characteristic On: false
[21/01/2025, 13:48:12] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Got value for characteristic Active: 1
[21/01/2025, 13:48:12] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Got value for characteristic Brightness: 29
[21/01/2025, 13:48:12] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Got value for characteristic RotationSpeed: 50
```

Much the same...  This time I just changed the rotation speed to 75 during the discovery.  And it still sent 50 to HomeKit.

**Comment by ZeliardM** [comment]
Ok, at least all four characteristics are correct on there now. The On and Brightness Characteristics are for the dimmer and Active and RotationSpeed are for the fan.

While a discovery is going on, the OnGet will return the current characteristics value. That value will only be updated during an OnSet event or the polling where it will use getSysInfo to pull the latest information from the device and update the characteristics.

That is the same for all the devices. The periodicDeviceDiscovery was only really being used to find devices and update offline statuses and remove stale devices or add new ones. I can see if I can add a way to check characteristic values and update them if needed, but that may take a bit.

I can see the case for this as if the device is updated during discovery, it would overwrite any old values and essentially never update the characteristic unless you change it again not during discovery.

**Comment by ZeliardM** [comment]
Try beta.32 and let me know if that makes any difference

**Comment by MichaelCWarren** [comment]
I added some logging and here is what I found.  

```
[21/01/2025, 14:49:38] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Previous Kasa Device for DeviceType.WallSwitch_192.168.75.63: {"sys_info":{"alias":"DeviceType.WallSwitch_192.168.75.63","child_num":2,"children":[{"alias":"Master Bedroom Fan","fan_speed_level":2,"id":"803B3E8D9C2FFF7B54EF338A07925F102322AEDE00","state":true},{"alias":"Master Bedroom Fan Light","brightness":29,"id":"803B3E8D9C2FFF7B54EF338A07925F102322AEDE01","state":false}],"device_id":"803B3E8D9C2FFF7B54EF338A07925F102322AEDE","device_type":"wallswitch","host":"192.168.75.63","hw_ver":"1.0","mac":"F0:09:0D:A9:19:F6","model":"KS240","sw_ver":"1.0.9"},"feature_info":{},"last_seen":"2025-01-21T19:49:14.374Z","offline":false}
[21/01/2025, 14:49:38] [KasaPython] STDOUT: Getting sys_info for host:  192.168.75.63
Serializing device None
Serializing child device Master Bedroom Fan
Serializing child device Master Bedroom Fan Light
Getting light info for device Master Bedroom Fan Light
[21/01/2025, 14:49:38] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] New Kasa Device for DeviceType.WallSwitch_192.168.75.63: {"sys_info":{"alias":"DeviceType.WallSwitch_192.168.75.63","child_num":2,"children":[{"alias":"Master Bedroom Fan","fan_speed_level":2,"id":"803B3E8D9C2FFF7B54EF338A07925F102322AEDE00","state":true},{"alias":"Master Bedroom Fan Light","brightness":29,"id":"803B3E8D9C2FFF7B54EF338A07925F102322AEDE01","state":false}],"device_id":"803B3E8D9C2FFF7B54EF338A07925F102322AEDE","device_type":"wallswitch","host":"192.168.75.63","hw_ver":"1.0","mac":"F0:09:0D:A9:19:F6","model":"KS240","sw_ver":"1.0.9"},"feature_info":{},"last_seen":"2025-01-21T19:49:14.374Z","offline":false}

[21/01/2025, 14:49:38] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Updated sys_info for device: DeviceType.WallSwitch_192.168.75.63
```

Before discovery the fan speed is 2, and because the previousKasaDevice has the same value, no update is done.


```
[21/01/2025, 14:49:38] [KasaPython] Discovering devices...
[21/01/2025, 14:49:45] [KasaPython] Finding discovered device with Platform Accessory DeviceType.WallSwitch_192.168.75.63
[21/01/2025, 14:49:45] [KasaPython] Discovered device DeviceType.WallSwitch_192.168.75.63
[21/01/2025, 14:49:45] [KasaPython] Updating Platform Accessory and HomeKit device statuses for DeviceType.WallSwitch_192.168.75.63
[21/01/2025, 14:49:45] [KasaPython] Setting HomeKit device DeviceType.WallSwitch_192.168.75.63 last seen time to now and marking as online
[21/01/2025, 14:49:45] [KasaPython] Setting Platform Accessory DeviceType.WallSwitch_192.168.75.63 last seen time to now and marking as online
[21/01/2025, 14:49:45] [KasaPython] Updating Platform Accessory DeviceType.WallSwitch_192.168.75.63
[21/01/2025, 14:49:45] [KasaPython] Platform Accessory and HomeKit device statuses for DeviceType.WallSwitch_192.168.75.63 updated successfully
[21/01/2025, 14:49:45] [KasaPython] Updating or creating HomeKit device DeviceType.WallSwitch_192.168.75.63
[21/01/2025, 14:49:45] [KasaPython] HomeKit device DeviceType.WallSwitch_192.168.75.63 already exists.
[21/01/2025, 14:49:45] [KasaPython] Updating existing HomeKit device DeviceType.WallSwitch_192.168.75.63
[21/01/2025, 14:49:45] [KasaPython] Finished periodic device discovery
```

I change the value during discover to 3, but since we are simply setting existingDevice.kasaDevice (platform.ts:405 & 409) to the discovered value, the "previous" value in the next update is the new one.  As seen below.

```

[21/01/2025, 14:49:50] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Previous Kasa Device for DeviceType.WallSwitch_192.168.75.63: {"sys_info":{"alias":"DeviceType.WallSwitch_192.168.75.63","child_num":2,"children":[{"alias":"Master Bedroom Fan","fan_speed_level":3,"id":"803B3E8D9C2FFF7B54EF338A07925F102322AEDE00","state":true},{"alias":"Master Bedroom Fan Light","brightness":29,"id":"803B3E8D9C2FFF7B54EF338A07925F102322AEDE01","state":false}],"device_id":"803B3E8D9C2FFF7B54EF338A07925F102322AEDE","device_type":"wallswitch","host":"192.168.75.63","hw_ver":"1.0","mac":"F0:09:0D:A9:19:F6","model":"KS240","sw_ver":"1.0.9"},"feature_info":{},"last_seen":"2025-01-21T19:49:44.366Z","offline":false}
[21/01/2025, 14:49:51] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] New Kasa Device for DeviceType.WallSwitch_192.168.75.63: {"sys_info":{"alias":"DeviceType.WallSwitch_192.168.75.63","child_num":2,"children":[{"alias":"Master Bedroom Fan","fan_speed_level":3,"id":"803B3E8D9C2FFF7B54EF338A07925F102322AEDE00","state":true},{"alias":"Master Bedroom Fan Light","brightness":29,"id":"803B3E8D9C2FFF7B54EF338A07925F102322AEDE01","state":false}],"device_id":"803B3E8D9C2FFF7B54EF338A07925F102322AEDE","device_type":"wallswitch","host":"192.168.75.63","hw_ver":"1.0","mac":"F0:09:0D:A9:19:F6","model":"KS240","sw_ver":"1.0.9"},"feature_info":{},"last_seen":"2025-01-21T19:49:44.366Z","offline":false}
```

**Comment by ZeliardM** [comment]
Was that with beta.32 or 31?

**Comment by MichaelCWarren** [comment]
That was with 31, I tried with 32 and it was the same.

**Comment by ZeliardM** [comment]
Ok, I'll mess with the updates of the devices during discovery and see about updating the characteristic values at that time as well.

**Comment by ZeliardM** [comment]
Give beta.33 a shot and let me know.

**Comment by MichaelCWarren** [comment]
Looks like it attempts to update the fan speed after the discover, but it just sets it to the previously known value.  Not the new/actual one.

**Comment by ZeliardM** [comment]
Ok, what does the log say for the other values?

**Comment by ZeliardM** [comment]
I forgot to add in the conversions, I'll make that change and push another beta.

**Comment by MichaelCWarren** [comment]
```
[21/01/2025, 19:36:18] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Setting value for characteristic RotationSpeed to 3
[21/01/2025, 19:36:18] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Updating [Fanv2.Rotation Speed] on Master Bedroom Fan to 50
[21/01/2025, 19:36:18] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Setting value for characteristic Active to true
[21/01/2025, 19:36:18] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Updating [Fanv2.Active] on Master Bedroom Fan to 1
[21/01/2025, 19:36:18] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Setting value for characteristic On to false
[21/01/2025, 19:36:18] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Updating [Lightbulb.On] on Master Bedroom Fan Light to false
[21/01/2025, 19:36:18] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Setting value for characteristic Brightness to 29
[21/01/2025, 19:36:18] [KasaPython] [DeviceType.WallSwitch_192.168.75.63] Updating [Lightbulb.Brightness] on Master Bedroom Fan Light to 29
```

yes, it looks like it's trying to go to 75% here like it should, but the next line only says 50...

This will probably affect other devices as well, not just the fan, right?

**Comment by ZeliardM** [comment]
Yea, I got to get the conversion correct there. Nah, this is the only device with these types of conversions and I haven't changed the other device files.

**Comment by MichaelCWarren** [comment]
Oh, I meant this update during discovery problem.  Looking at the code though, it looks like you're on it.

**Comment by ZeliardM** [comment]
@MichaelCWarren give beta.34 a shot and let me know.

**Comment by MichaelCWarren** [comment]
@ZeliardM Looks good to me so far.  I'll keep an eye on it, but I'd say we're probably good.  Thanks.  Good work!

**Comment by ZeliardM** [comment]
@MichaelCWarren Excellent, glad that works now and I'll keep an eye on everything else and clean up code as I go along getting ready for a full release.

**Comment by ZeliardM** [comment]
Give beta.35 a shot and let me know if everything looks good, I made some other modifications.

**Comment by ZeliardM** [comment]
@MichaelCWarren if beta.36 looks good, do you think we can close this one out?

**Comment by MichaelCWarren** [comment]
Yep, I think we can
-Michael



On Jan 23, 2025, at 1:14 PM, ZeliardM ***@***.***> wrote:



@MichaelCWarren<https://github.com/MichaelCWarren> if beta.36 looks good, do you think we can close this one out?
